
//
// designTokens/ios-swift/DesignSystem+Class.swift
//

// Do not edit directly
// Generated on Tue, 21 Mar 2023 10:48:19 GMT


import UIKit

public class DesignSystemClass {
    public static let accent20Blur = 18
    public static let accent20Color = #9dd4d833
    public static let accent20Spread = 50
    public static let accent20Type = dropShadow
    public static let accent20X = 0
    public static let accent20Y = 8
    public static let accentA100 = #9dd4d8
    public static let accentA200 = #73c2c7
    public static let accentA300 = #56b5bc
    public static let accentA400 = #3c7f84
    public static let accentA50 = #eef8f8
    public static let accentA500 = #346e73
    public static let accentA75 = #bae1e4
    public static let baseBoldFontFamily = Roboto
    public static let baseBoldFontSize = 16
    public static let baseBoldFontWeight = Bold
    public static let baseBoldLineHeight = 150%
    public static let baseMediumFontFamily = Roboto
    public static let baseMediumFontSize = 16
    public static let baseMediumFontWeight = Medium
    public static let baseMediumLineHeight = 150%
    public static let baseRegularFontFamily = Roboto
    public static let baseRegularFontSize = 16
    public static let baseRegularFontWeight = Regular
    public static let baseRegularLineHeight = 150%
    public static let baseSemiBoldFontFamily = Roboto
    public static let baseSemiBoldFontSize = 16
    public static let baseSemiBoldFontWeight = SemiBold
    public static let baseSemiBoldLineHeight = 150%
    public static let black = #000000
    public static let body = #061216
    public static let borderDashAccent01Color = #bae1e4
    public static let borderDashAccent01Style = dashed
    public static let borderDashAccent01Width = 1
    public static let borderDashPrimary01Color = #97adb4
    public static let borderDashPrimary01Style = dashed
    public static let borderDashPrimary01Width = 1
    public static let borderLineAccent1Color = #bae1e4
    public static let borderLineAccent1Style = solid
    public static let borderLineAccent1Width = 1
    public static let borderLinePrimary01Color = #97adb4
    public static let borderLinePrimary01Style = solid
    public static let borderLinePrimary01Width = 1
    public static let borderRadius12 = 12
    public static let borderRadius16 = 16
    public static let borderRadius20 = 20
    public static let borderRadius24 = 24
    public static let borderRadius28 = 28
    public static let borderRadius32 = 32
    public static let borderRadius4 = 4
    public static let borderRadius8 = 8
    public static let borderWidth01 = 1
    public static let borderWidth02 = 2
    public static let borderWidth03 = 3
    public static let borderWidth04 = 4
    public static let btnSpacing12 = 12
    public static let btnSpacing16 = 16
    public static let btnSpacing20 = 20
    public static let btnSpacing24 = 24
    public static let btnSpacing4 = 4
    public static let btnSpacing8 = 8
    public static let buttonBorderDangerActiveColor = #ed3030
    public static let buttonBorderDangerActiveStyle = solid
    public static let buttonBorderDangerActiveWidth = 1
    public static let buttonBorderDangerHoverColor = #a62222
    public static let buttonBorderDangerHoverStyle = solid
    public static let buttonBorderDangerHoverWidth = 1
    public static let buttonBorderPrimaryActiveColor = #56b5bc
    public static let buttonBorderPrimaryActiveStyle = solid
    public static let buttonBorderPrimaryActiveWidth = 1
    public static let buttonBorderPrimaryHoverColor = #3c7f84
    public static let buttonBorderPrimaryHoverStyle = solid
    public static let buttonBorderPrimaryHoverWidth = 1
    public static let buttonBorderRadiusSm = 4
    public static let buttonBorderRadiusXxxl = 24
    public static let buttonBorderSecondaryActiveColor = #ef8b6d
    public static let buttonBorderSecondaryActiveStyle = solid
    public static let buttonBorderSecondaryActiveWidth = 1
    public static let buttonBorderSecondaryHoverColor = #a7614c
    public static let buttonBorderSecondaryHoverStyle = solid
    public static let buttonBorderSecondaryHoverWidth = 1
    public static let buttonBorderSuccessActiveColor = #79c131
    public static let buttonBorderSuccessActiveStyle = solid
    public static let buttonBorderSuccessActiveWidth = 1
    public static let buttonBorderSuccessHoverColor = #558722
    public static let buttonBorderSuccessHoverStyle = solid
    public static let buttonBorderSuccessHoverWidth = 1
    public static let buttonBorderWidthSm = 1
    public static let buttonDangerActive = #ed3030
    public static let buttonDangerClick = #f8aaaa
    public static let buttonDangerHover = #a62222
    public static let buttonDangerHoverAlt = #fdeaea
    public static let buttonDisabled = #c1c4ce
    public static let buttonInfoActive = #1eaaf9
    public static let buttonInfoClick = #a3dcfd
    public static let buttonInfoHover = #1577ae
    public static let buttonInfoHoverAlt = #e9f7fe
    public static let buttonPrimaryActive = #56b5bc
    public static let buttonPrimaryClick = #bae1e4
    public static let buttonPrimaryHover = #3c7f84
    public static let buttonPrimaryHoverAlt = #eef8f8
    public static let buttonSecondaryActive = #ef8b6d
    public static let buttonSecondaryClick = #f8cfc3
    public static let buttonSecondaryHover = #a7614c
    public static let buttonSecondaryHoverAlt = #fdf3f0
    public static let buttonSuccessActive = #79c131
    public static let buttonSuccessClick = #c8e6ab
    public static let buttonSuccessHover = #558722
    public static let buttonSuccessHoverAlt = #f2f9ea
    public static let buttonTextWhite = #fff
    public static let colorAccent100 = UIColor(red: 0.616, green: 0.831, blue: 0.847, alpha: 1)
    public static let colorAccent200 = UIColor(red: 0.451, green: 0.761, blue: 0.780, alpha: 1)
    public static let colorAccent300 = UIColor(red: 0.337, green: 0.710, blue: 0.737, alpha: 1)
    public static let colorAccent400 = UIColor(red: 0.235, green: 0.498, blue: 0.518, alpha: 1)
    public static let colorAccent50 = UIColor(red: 0.933, green: 0.973, blue: 0.973, alpha: 1)
    public static let colorAccent500 = UIColor(red: 0.204, green: 0.431, blue: 0.451, alpha: 1)
    public static let colorAccent75 = UIColor(red: 0.729, green: 0.882, blue: 0.894, alpha: 1)
    public static let colorBlack = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorDanger100 = UIColor(red: 0.961, green: 0.529, blue: 0.529, alpha: 1)
    public static let colorDanger200 = UIColor(red: 0.941, green: 0.325, blue: 0.325, alpha: 1)
    public static let colorDanger300 = UIColor(red: 0.929, green: 0.188, blue: 0.188, alpha: 1)
    public static let colorDanger400 = UIColor(red: 0.651, green: 0.133, blue: 0.133, alpha: 1)
    public static let colorDanger50 = UIColor(red: 0.992, green: 0.918, blue: 0.918, alpha: 1)
    public static let colorDanger500 = UIColor(red: 0.569, green: 0.114, blue: 0.114, alpha: 1)
    public static let colorDanger75 = UIColor(red: 0.973, green: 0.667, blue: 0.667, alpha: 1)
    public static let colorGNormal180 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorGPrimary180 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorGPrimary270 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorGPrimary45 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorGPrimary90 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorGSecondary180 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorGSecondary270 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorGSecondary45 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorGSecondary90 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorInfo100 = UIColor(red: 0.490, green: 0.808, blue: 0.988, alpha: 1)
    public static let colorInfo200 = UIColor(red: 0.267, green: 0.722, blue: 0.980, alpha: 1)
    public static let colorInfo300 = UIColor(red: 0.118, green: 0.667, blue: 0.976, alpha: 1)
    public static let colorInfo400 = UIColor(red: 0.082, green: 0.467, blue: 0.682, alpha: 1)
    public static let colorInfo50 = UIColor(red: 0.914, green: 0.969, blue: 0.996, alpha: 1)
    public static let colorInfo500 = UIColor(red: 0.071, green: 0.408, blue: 0.596, alpha: 1)
    public static let colorInfo75 = UIColor(red: 0.639, green: 0.863, blue: 0.992, alpha: 1)
    public static let colorNeutral10 = UIColor(red: 0.980, green: 0.980, blue: 0.984, alpha: 1)
    public static let colorNeutral100 = UIColor(red: 0.471, green: 0.494, blue: 0.584, alpha: 1)
    public static let colorNeutral20 = UIColor(red: 0.961, green: 0.961, blue: 0.969, alpha: 1)
    public static let colorNeutral200 = UIColor(red: 0.412, green: 0.439, blue: 0.537, alpha: 1)
    public static let colorNeutral30 = UIColor(red: 0.922, green: 0.925, blue: 0.937, alpha: 1)
    public static let colorNeutral300 = UIColor(red: 0.353, green: 0.384, blue: 0.490, alpha: 1)
    public static let colorNeutral40 = UIColor(red: 0.875, green: 0.878, blue: 0.898, alpha: 1)
    public static let colorNeutral400 = UIColor(red: 0.306, green: 0.337, blue: 0.451, alpha: 1)
    public static let colorNeutral50 = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    public static let colorNeutral500 = UIColor(red: 0.247, green: 0.282, blue: 0.404, alpha: 1)
    public static let colorNeutral60 = UIColor(red: 0.698, green: 0.710, blue: 0.761, alpha: 1)
    public static let colorNeutral600 = UIColor(red: 0.196, green: 0.235, blue: 0.365, alpha: 1)
    public static let colorNeutral70 = UIColor(red: 0.647, green: 0.663, blue: 0.722, alpha: 1)
    public static let colorNeutral700 = UIColor(red: 0.129, green: 0.169, blue: 0.314, alpha: 1)
    public static let colorNeutral80 = UIColor(red: 0.588, green: 0.608, blue: 0.675, alpha: 1)
    public static let colorNeutral800 = UIColor(red: 0.071, green: 0.114, blue: 0.267, alpha: 1)
    public static let colorNeutral90 = UIColor(red: 0.529, green: 0.553, blue: 0.627, alpha: 1)
    public static let colorNeutral900 = UIColor(red: 0.020, green: 0.067, blue: 0.227, alpha: 1)
    public static let colorPrimary100 = UIColor(red: 0.424, green: 0.545, blue: 0.580, alpha: 1)
    public static let colorPrimary200 = UIColor(red: 0.176, green: 0.349, blue: 0.400, alpha: 1)
    public static let colorPrimary300 = UIColor(red: 0.008, green: 0.216, blue: 0.278, alpha: 1)
    public static let colorPrimary400 = UIColor(red: 0.004, green: 0.153, blue: 0.196, alpha: 1)
    public static let colorPrimary50 = UIColor(red: 0.902, green: 0.922, blue: 0.929, alpha: 1)
    public static let colorPrimary500 = UIColor(red: 0.004, green: 0.133, blue: 0.169, alpha: 1)
    public static let colorPrimary75 = UIColor(red: 0.592, green: 0.678, blue: 0.706, alpha: 1)
    public static let colorSecondary100 = UIColor(red: 0.965, green: 0.737, blue: 0.667, alpha: 1)
    public static let colorSecondary200 = UIColor(red: 0.949, green: 0.624, blue: 0.525, alpha: 1)
    public static let colorSecondary300 = UIColor(red: 0.937, green: 0.545, blue: 0.427, alpha: 1)
    public static let colorSecondary400 = UIColor(red: 0.655, green: 0.380, blue: 0.298, alpha: 1)
    public static let colorSecondary50 = UIColor(red: 0.992, green: 0.953, blue: 0.941, alpha: 1)
    public static let colorSecondary500 = UIColor(red: 0.573, green: 0.333, blue: 0.259, alpha: 1)
    public static let colorSecondary75 = UIColor(red: 0.973, green: 0.812, blue: 0.765, alpha: 1)
    public static let colorSuccess100 = UIColor(red: 0.694, green: 0.859, blue: 0.533, alpha: 1)
    public static let colorSuccess200 = UIColor(red: 0.565, green: 0.800, blue: 0.329, alpha: 1)
    public static let colorSuccess300 = UIColor(red: 0.475, green: 0.757, blue: 0.192, alpha: 1)
    public static let colorSuccess400 = UIColor(red: 0.333, green: 0.529, blue: 0.133, alpha: 1)
    public static let colorSuccess50 = UIColor(red: 0.949, green: 0.976, blue: 0.918, alpha: 1)
    public static let colorSuccess500 = UIColor(red: 0.290, green: 0.463, blue: 0.118, alpha: 1)
    public static let colorSuccess75 = UIColor(red: 0.784, green: 0.902, blue: 0.671, alpha: 1)
    public static let colorWarning100 = UIColor(red: 1.000, green: 0.859, blue: 0.525, alpha: 1)
    public static let colorWarning200 = UIColor(red: 1.000, green: 0.800, blue: 0.322, alpha: 1)
    public static let colorWarning300 = UIColor(red: 1.000, green: 0.757, blue: 0.180, alpha: 1)
    public static let colorWarning400 = UIColor(red: 0.702, green: 0.529, blue: 0.125, alpha: 1)
    public static let colorWarning50 = UIColor(red: 1.000, green: 0.976, blue: 0.918, alpha: 1)
    public static let colorWarning500 = UIColor(red: 0.612, green: 0.463, blue: 0.110, alpha: 1)
    public static let colorWarning75 = UIColor(red: 1.000, green: 0.902, blue: 0.663, alpha: 1)
    public static let colorWhite = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let danger20Blur = 18
    public static let danger20Color = #f5878733
    public static let danger20Spread = 50
    public static let danger20Type = dropShadow
    public static let danger20X = 0
    public static let danger20Y = 8
    public static let dangerD100 = #f58787
    public static let dangerD200 = #f05353
    public static let dangerD300 = #ed3030
    public static let dangerD400 = #a62222
    public static let dangerD50 = #fdeaea
    public static let dangerD500 = #911d1d
    public static let dangerD75 = #f8aaaa
    public static let fontColorShadeAccent = "#3c7f84"
    public static let fontColorShadeDanger = "#a62222"
    public static let fontColorShadeInfo = "#1577ae"
    public static let fontColorShadePrimary = "#012732"
    public static let fontColorShadeSecondary = "#a7614c"
    public static let fontColorShadeSuccess = "#558722"
    public static let fontColorShadeWarning = "#b38720"
    public static let fontDefaultBlack = "#000000"
    public static let fontDefaultColor = "#061216"
    public static let fontDefaultWhite = "#fff"
    public static let fontFamilyCourier = Courier Prime
    public static let fontFamilyRoboto = Roboto
    public static let fontSize11px = 11
    public static let fontSize13px = 13
    public static let fontSize14px = 14
    public static let fontSize16px = 16
    public static let fontSize18px = 18
    public static let fontSize20px = 20
    public static let fontSize23px = 23
    public static let fontSize26px = 26
    public static let fontSize29px = 29
    public static let fontSize32px = 32
    public static let fontSize36px = 36
    public static let fontTint01 = "#c1c4ce"
    public static let fontTint02 = "#b2b5c2"
    public static let fontTint03 = "#a5a9b8"
    public static let fontTint04 = "#969bac"
    public static let fontUnderline = "underline"
    public static let fontUppercase = "uppercase"
    public static let fontWeightBold = Bold
    public static let fontWeightItalic = Italic
    public static let fontWeightMedium = Medium
    public static let fontWeightRegular = Regular
    public static let fontWeightSemiBold = SemiBold
    public static let gradientNormal180 = linear-gradient(180deg, #fafafb 0%, #c1c4ce 100%)
    public static let gradientPrimary180 = linear-gradient(180deg, #c1c4ce 0%, #56b5bc 100%)
    public static let gradientPrimary270 = linear-gradient(270deg, #fff 0%, #56b5bc 100%)
    public static let gradientPrimary45 = linear-gradient(45deg, #fff 0%, #56b5bc 100%)
    public static let gradientPrimary90 = linear-gradient(90deg, #fff 0%, #56b5bc 100%)
    public static let gradientSecondary180 = linear-gradient(180deg, #fff 0%, #ef8b6d 100%)
    public static let gradientSecondary270 = linear-gradient(270deg, #fff 0%, #ef8b6d 100%)
    public static let gradientSecondary45 = linear-gradient(45deg, #fff 0%, #ef8b6d 100%)
    public static let gradientSecondary90 = linear-gradient(90deg, #fff 0%, #ef8b6d 100%)
    public static let h1BoldFontFamily = Roboto
    public static let h1BoldFontSize = 36
    public static let h1BoldFontWeight = Bold
    public static let h1BoldLineHeight = 140%
    public static let h1MediumFontFamily = Roboto
    public static let h1MediumFontSize = 36
    public static let h1MediumFontWeight = Medium
    public static let h1MediumLineHeight = 140%
    public static let h1RegularFontFamily = Roboto
    public static let h1RegularFontSize = 36
    public static let h1RegularFontWeight = Regular
    public static let h1RegularLineHeight = 140%
    public static let h1SemiBoldFontFamily = Roboto
    public static let h1SemiBoldFontSize = 36
    public static let h1SemiBoldFontWeight = SemiBold
    public static let h1SemiBoldLineHeight = 140%
    public static let h2BoldFontFamily = Roboto
    public static let h2BoldFontSize = 32
    public static let h2BoldFontWeight = Bold
    public static let h2BoldLineHeight = 140%
    public static let h2MediumFontFamily = Roboto
    public static let h2MediumFontSize = 32
    public static let h2MediumFontWeight = Medium
    public static let h2MediumLineHeight = 140%
    public static let h2RegularFontFamily = Roboto
    public static let h2RegularFontSize = 32
    public static let h2RegularFontWeight = Regular
    public static let h2RegularLineHeight = 140%
    public static let h2SemiBoldFontFamily = Roboto
    public static let h2SemiBoldFontSize = 32
    public static let h2SemiBoldFontWeight = SemiBold
    public static let h2SemiBoldLineHeight = 140%
    public static let h3BoldFontFamily = Roboto
    public static let h3BoldFontSize = 29
    public static let h3BoldFontWeight = Bold
    public static let h3BoldLineHeight = 140%
    public static let h3MediumFontFamily = Roboto
    public static let h3MediumFontSize = 29
    public static let h3MediumFontWeight = Medium
    public static let h3MediumLineHeight = 140%
    public static let h3RegularFontFamily = Roboto
    public static let h3RegularFontSize = 29
    public static let h3RegularFontWeight = Regular
    public static let h3RegularLineHeight = 140%
    public static let h3SemiBoldFontFamily = Roboto
    public static let h3SemiBoldFontSize = 29
    public static let h3SemiBoldFontWeight = SemiBold
    public static let h3SemiBoldLineHeight = 140%
    public static let h4BoldFontFamily = Roboto
    public static let h4BoldFontSize = 26
    public static let h4BoldFontWeight = Bold
    public static let h4BoldLineHeight = 140%
    public static let h4MediumFontFamily = Roboto
    public static let h4MediumFontSize = 26
    public static let h4MediumFontWeight = Medium
    public static let h4MediumLineHeight = 140%
    public static let h4RegularFontFamily = Roboto
    public static let h4RegularFontSize = 26
    public static let h4RegularFontWeight = Regular
    public static let h4RegularLineHeight = 140%
    public static let h4SemiBoldFontFamily = Roboto
    public static let h4SemiBoldFontSize = 26
    public static let h4SemiBoldFontWeight = SemiBold
    public static let h4SemiBoldLineHeight = 140%
    public static let h5BoldFontFamily = Roboto
    public static let h5BoldFontSize = 23
    public static let h5BoldFontWeight = Bold
    public static let h5BoldLineHeight = 140%
    public static let h5MediumFontFamily = Roboto
    public static let h5MediumFontSize = 23
    public static let h5MediumFontWeight = Medium
    public static let h5MediumLineHeight = 140%
    public static let h5RegularFontFamily = Roboto
    public static let h5RegularFontSize = 23
    public static let h5RegularFontWeight = Regular
    public static let h5RegularLineHeight = 140%
    public static let h5SemiBoldFontFamily = Roboto
    public static let h5SemiBoldFontSize = 23
    public static let h5SemiBoldFontWeight = SemiBold
    public static let h5SemiBoldLineHeight = 140%
    public static let h6BoldFontFamily = Roboto
    public static let h6BoldFontSize = 20
    public static let h6BoldFontWeight = Bold
    public static let h6BoldLineHeight = 140%
    public static let h6MediumFontFamily = Roboto
    public static let h6MediumFontSize = 20
    public static let h6MediumFontWeight = Medium
    public static let h6MediumLineHeight = 140%
    public static let h6RegularFontFamily = Roboto
    public static let h6RegularFontSize = 20
    public static let h6RegularFontWeight = Regular
    public static let h6RegularLineHeight = 140%
    public static let h6SemiBoldFontFamily = Roboto
    public static let h6SemiBoldFontSize = 20
    public static let h6SemiBoldFontWeight = SemiBold
    public static let h6SemiBoldLineHeight = 140%
    public static let info20Blur = 18
    public static let info20Color = #7dcefc33
    public static let info20Spread = 50
    public static let info20Type = dropShadow
    public static let info20X = 0
    public static let info20Y = 8
    public static let infoI100 = #7dcefc
    public static let infoI200 = #44b8fa
    public static let infoI300 = #1eaaf9
    public static let infoI400 = #1577ae
    public static let infoI50 = #e9f7fe
    public static let infoI500 = #126898
    public static let infoI75 = #a3dcfd
    public static let labelBoldFontFamily = Roboto
    public static let labelBoldFontSize = 13
    public static let labelBoldFontWeight = Bold
    public static let labelBoldLineHeight = 140%
    public static let labelMediumFontFamily = Roboto
    public static let labelMediumFontSize = 13
    public static let labelMediumFontWeight = Medium
    public static let labelMediumLineHeight = 140%
    public static let labelRegularFontFamily = Roboto
    public static let labelRegularFontSize = 13
    public static let labelRegularFontWeight = Regular
    public static let labelRegularLineHeight = 140%
    public static let labelSemiBoldFontFamily = Roboto
    public static let labelSemiBoldFontSize = 13
    public static let labelSemiBoldFontWeight = SemiBold
    public static let labelSemiBoldLineHeight = 140%
    public static let largeBoldFontFamily = Roboto
    public static let largeBoldFontSize = 18
    public static let largeBoldFontWeight = Bold
    public static let largeBoldLineHeight = 150%
    public static let largeMediumFontFamily = Roboto
    public static let largeMediumFontSize = 18
    public static let largeMediumFontWeight = Medium
    public static let largeMediumLineHeight = 150%
    public static let largeRegularFontFamily = Roboto
    public static let largeRegularFontSize = 18
    public static let largeRegularFontWeight = Regular
    public static let largeRegularLineHeight = 150%
    public static let largeSemiBoldFontFamily = Roboto
    public static let largeSemiBoldFontSize = 18
    public static let largeSemiBoldFontWeight = SemiBold
    public static let largeSemiBoldLineHeight = 150%
    public static let layoutBackgroundAccent = #eef8f8
    public static let layoutBackgroundN10 = #fafafb
    public static let layoutBackgroundN20 = #f5f5f7
    public static let layoutBackgroundN30 = #ebecef
    public static let layoutBackgroundN40 = #dfe0e5
    public static let layoutBackgroundN50 = #c1c4ce
    public static let layoutBackgroundPrimary = #e6ebed
    public static let layoutBackgroundSecondary = #fdf3f0
    public static let layoutBackgroundWhite = #fff
    public static let layoutBorderRadius12 = 12
    public static let layoutBorderRadius16 = 16
    public static let layoutBorderRadius20 = 20
    public static let layoutBorderRadius24 = 24
    public static let layoutBorderRadius28 = 28
    public static let layoutBorderRadius32 = 32
    public static let layoutBorderRadius4 = 4
    public static let layoutBorderRadius8 = 8
    public static let layoutBorderWidth01 = 1
    public static let layoutBorderWidth02 = 2
    public static let layoutBorderWidth03 = 3
    public static let layoutBorderWidth04 = 4
    public static let layoutBoxShadowAccentBlur = 18
    public static let layoutBoxShadowAccentColor = #9dd4d833
    public static let layoutBoxShadowAccentSpread = 50
    public static let layoutBoxShadowAccentType = dropShadow
    public static let layoutBoxShadowAccentX = 0
    public static let layoutBoxShadowAccentY = 8
    public static let layoutBoxShadowDangerBlur = 18
    public static let layoutBoxShadowDangerColor = #f5878733
    public static let layoutBoxShadowDangerSpread = 50
    public static let layoutBoxShadowDangerType = dropShadow
    public static let layoutBoxShadowDangerX = 0
    public static let layoutBoxShadowDangerY = 8
    public static let layoutBoxShadowInfoBlur = 18
    public static let layoutBoxShadowInfoColor = #7dcefc33
    public static let layoutBoxShadowInfoSpread = 50
    public static let layoutBoxShadowInfoType = dropShadow
    public static let layoutBoxShadowInfoX = 0
    public static let layoutBoxShadowInfoY = 8
    public static let layoutBoxShadowPrimary10Blur = 15
    public static let layoutBoxShadowPrimary10Color = #2d596614
    public static let layoutBoxShadowPrimary10Spread = 0
    public static let layoutBoxShadowPrimary10Type = dropShadow
    public static let layoutBoxShadowPrimary10X = -3
    public static let layoutBoxShadowPrimary10Y = 8
    public static let layoutBoxShadowPrimary20Blur = 18
    public static let layoutBoxShadowPrimary20Color = #6c8b9433
    public static let layoutBoxShadowPrimary20Spread = 50
    public static let layoutBoxShadowPrimary20Type = dropShadow
    public static let layoutBoxShadowPrimary20X = 0
    public static let layoutBoxShadowPrimary20Y = 8
    public static let layoutBoxShadowPrimary5Blur = 18
    public static let layoutBoxShadowPrimary5Color = #2d59660d
    public static let layoutBoxShadowPrimary5Spread = 10
    public static let layoutBoxShadowPrimary5Type = dropShadow
    public static let layoutBoxShadowPrimary5X = 0
    public static let layoutBoxShadowPrimary5Y = 8
    public static let layoutBoxShadowSecondaryBlur = 18
    public static let layoutBoxShadowSecondaryColor = #f6bcaa33
    public static let layoutBoxShadowSecondarySpread = 50
    public static let layoutBoxShadowSecondaryType = dropShadow
    public static let layoutBoxShadowSecondaryX = 0
    public static let layoutBoxShadowSecondaryY = 8
    public static let layoutBoxShadowSuccess10Blur = 18
    public static let layoutBoxShadowSuccess10Color = #b1db8833
    public static let layoutBoxShadowSuccess10Spread = 2
    public static let layoutBoxShadowSuccess10Type = dropShadow
    public static let layoutBoxShadowSuccess10X = 0
    public static let layoutBoxShadowSuccess10Y = 4
    public static let layoutBoxShadowSuccess20Blur = 18
    public static let layoutBoxShadowSuccess20Color = #b1db8833
    public static let layoutBoxShadowSuccess20Spread = 50
    public static let layoutBoxShadowSuccess20Type = dropShadow
    public static let layoutBoxShadowSuccess20X = 0
    public static let layoutBoxShadowSuccess20Y = 8
    public static let layoutBoxShadowWarningBlur = 18
    public static let layoutBoxShadowWarningColor = #ffdb8633
    public static let layoutBoxShadowWarningSpread = 50
    public static let layoutBoxShadowWarningType = dropShadow
    public static let layoutBoxShadowWarningX = 0
    public static let layoutBoxShadowWarningY = 8
    public static let layoutDashedAccent01Color = #bae1e4
    public static let layoutDashedAccent01Style = dashed
    public static let layoutDashedAccent01Width = 1
    public static let layoutDashedPrimary01Color = #97adb4
    public static let layoutDashedPrimary01Style = dashed
    public static let layoutDashedPrimary01Width = 1
    public static let layoutOpacity10 = 10%
    public static let layoutOpacity100 = 100%
    public static let layoutOpacity20 = 20%
    public static let layoutOpacity30 = 30%
    public static let layoutOpacity40 = 40%
    public static let layoutOpacity50 = 50%
    public static let layoutOpacity60 = 60%
    public static let layoutOpacity70 = 70%
    public static let layoutOpacity80 = 80%
    public static let layoutOpacity90 = 90%
    public static let layoutSize100 = 100
    public static let layoutSize12 = 12
    public static let layoutSize16 = 16
    public static let layoutSize20 = 20
    public static let layoutSize200 = 200
    public static let layoutSize24 = 24
    public static let layoutSize28 = 28
    public static let layoutSize32 = 32
    public static let layoutSize36 = 36
    public static let layoutSize4 = 4
    public static let layoutSize40 = 40
    public static let layoutSize44 = 44
    public static let layoutSize48 = 48
    public static let layoutSize52 = 52
    public static let layoutSize56 = 56
    public static let layoutSize60 = 60
    public static let layoutSize8 = 8
    public static let layoutSolidAccent01Color = #bae1e4
    public static let layoutSolidAccent01Style = solid
    public static let layoutSolidAccent01Width = 1
    public static let layoutSolidPrimary01Color = #97adb4
    public static let layoutSolidPrimary01Style = solid
    public static let layoutSolidPrimary01Width = 1
    public static let layoutSpacing12 = 12
    public static let layoutSpacing16 = 16
    public static let layoutSpacing2 = 2
    public static let layoutSpacing20 = 20
    public static let layoutSpacing24 = 24
    public static let layoutSpacing28 = 28
    public static let layoutSpacing32 = 32
    public static let layoutSpacing36 = 36
    public static let layoutSpacing4 = 4
    public static let layoutSpacing40 = 40
    public static let layoutSpacing44 = 44
    public static let layoutSpacing48 = 48
    public static let layoutSpacing52 = 52
    public static let layoutSpacing56 = 56
    public static let layoutSpacing60 = 60
    public static let layoutSpacing8 = 8
    public static let layoutSpacingMinus12 = -12
    public static let layoutSpacingMinus16 = -16
    public static let layoutSpacingMinus2 = -2
    public static let layoutSpacingMinus20 = -20
    public static let layoutSpacingMinus24 = -24
    public static let layoutSpacingMinus28 = -28
    public static let layoutSpacingMinus32 = -32
    public static let layoutSpacingMinus36 = -36
    public static let layoutSpacingMinus4 = -4
    public static let layoutSpacingMinus40 = -40
    public static let layoutSpacingMinus44 = -44
    public static let layoutSpacingMinus48 = -48
    public static let layoutSpacingMinus52 = -52
    public static let layoutSpacingMinus56 = -56
    public static let layoutSpacingMinus60 = -60
    public static let layoutSpacingMinus8 = -8
    public static let letterSpacing0 = 0%
    public static let letterSpacing10 = 5%
    public static let lineHeight140 = 140%
    public static let lineHeight150 = 150%
    public static let neutralN0 = #ffffff
    public static let neutralN10 = #fafafb
    public static let neutralN100 = #787e95
    public static let neutralN20 = #f5f5f7
    public static let neutralN200 = #697089
    public static let neutralN30 = #ebecef
    public static let neutralN300 = #5a627d
    public static let neutralN40 = #dfe0e5
    public static let neutralN400 = #4e5673
    public static let neutralN50 = #c1c4ce
    public static let neutralN500 = #3f4867
    public static let neutralN60 = #b2b5c2
    public static let neutralN600 = #323c5d
    public static let neutralN70 = #a5a9b8
    public static let neutralN700 = #212b50
    public static let neutralN80 = #969bac
    public static let neutralN800 = #121d44
    public static let neutralN90 = #878da0
    public static let neutralN900 = #05113a
    public static let opacity10 = 10%
    public static let opacity100 = 100%
    public static let opacity20 = 20%
    public static let opacity30 = 30%
    public static let opacity40 = 40%
    public static let opacity50 = 50%
    public static let opacity60 = 60%
    public static let opacity70 = 70%
    public static let opacity80 = 80%
    public static let opacity90 = 90%
    public static let primary10LeftBlur = 15
    public static let primary10LeftColor = #2d596614
    public static let primary10LeftSpread = 0
    public static let primary10LeftType = dropShadow
    public static let primary10LeftX = -3
    public static let primary10LeftY = 8
    public static let primary20Blur = 18
    public static let primary20Color = #6c8b9433
    public static let primary20Spread = 50
    public static let primary20Type = dropShadow
    public static let primary20X = 0
    public static let primary20Y = 8
    public static let primary5Blur = 18
    public static let primary5Color = #2d59660d
    public static let primary5Spread = 10
    public static let primary5Type = dropShadow
    public static let primary5X = 0
    public static let primary5Y = 8
    public static let primaryP100 = #6c8b94
    public static let primaryP200 = #2d5966
    public static let primaryP300 = #023747
    public static let primaryP400 = #012732
    public static let primaryP50 = #e6ebed
    public static let primaryP500 = #01222b
    public static let primaryP75 = #97adb4
    public static let refSize100 = 100
    public static let refSize1000 = 1000
    public static let refSize12 = 12
    public static let refSize16 = 16
    public static let refSize20 = 20
    public static let refSize200 = 200
    public static let refSize24 = 24
    public static let refSize28 = 28
    public static let refSize300 = 300
    public static let refSize32 = 32
    public static let refSize36 = 36
    public static let refSize4 = 4
    public static let refSize40 = 40
    public static let refSize400 = 400
    public static let refSize44 = 44
    public static let refSize48 = 48
    public static let refSize500 = 500
    public static let refSize52 = 52
    public static let refSize56 = 56
    public static let refSize60 = 60
    public static let refSize600 = 600
    public static let refSize64 = 64
    public static let refSize68 = 68
    public static let refSize700 = 700
    public static let refSize72 = 72
    public static let refSize76 = 76
    public static let refSize8 = 8
    public static let refSize80 = 80
    public static let refSize800 = 800
    public static let refSize84 = 84
    public static let refSize88 = 88
    public static let refSize900 = 900
    public static let refSize92 = 92
    public static let refSize96 = 96
    public static let refSpacing12 = 12
    public static let refSpacing16 = 16
    public static let refSpacing2 = 2
    public static let refSpacing20 = 20
    public static let refSpacing24 = 24
    public static let refSpacing28 = 28
    public static let refSpacing32 = 32
    public static let refSpacing36 = 36
    public static let refSpacing4 = 4
    public static let refSpacing40 = 40
    public static let refSpacing44 = 44
    public static let refSpacing48 = 48
    public static let refSpacing52 = 52
    public static let refSpacing56 = 56
    public static let refSpacing60 = 60
    public static let refSpacing64 = 64
    public static let refSpacing68 = 68
    public static let refSpacing72 = 72
    public static let refSpacing76 = 76
    public static let refSpacing8 = 8
    public static let refSpacing80 = 80
    public static let secondary20Blur = 18
    public static let secondary20Color = #f6bcaa33
    public static let secondary20Spread = 50
    public static let secondary20Type = dropShadow
    public static let secondary20X = 0
    public static let secondary20Y = 8
    public static let secondaryS100 = #f6bcaa
    public static let secondaryS200 = #f29f86
    public static let secondaryS300 = #ef8b6d
    public static let secondaryS400 = #a7614c
    public static let secondaryS50 = #fdf3f0
    public static let secondaryS500 = #925542
    public static let secondaryS75 = #f8cfc3
    public static let smallBoldFontFamily = Roboto
    public static let smallBoldFontSize = 14
    public static let smallBoldFontWeight = Bold
    public static let smallBoldLineHeight = 150%
    public static let smallCourierBoldFontFamily = Courier Prime
    public static let smallCourierBoldFontSize = 14
    public static let smallCourierBoldFontWeight = Bold
    public static let smallCourierBoldLetterSpacing = 0%
    public static let smallCourierBoldLineHeight = 150%
    public static let smallCourierRegularFontFamily = Courier Prime
    public static let smallCourierRegularFontSize = 14
    public static let smallCourierRegularFontWeight = Regular
    public static let smallCourierRegularLetterSpacing = 0%
    public static let smallCourierRegularLineHeight = 140%
    public static let smallCourierRegularitalicFontFamily = Courier Prime
    public static let smallCourierRegularitalicFontSize = 14
    public static let smallCourierRegularitalicFontWeight = Italic
    public static let smallCourierRegularitalicLetterSpacing = 0%
    public static let smallCourierRegularitalicLineHeight = 140%
    public static let smallMediumFontFamily = Roboto
    public static let smallMediumFontSize = 14
    public static let smallMediumFontWeight = Medium
    public static let smallMediumLineHeight = 150%
    public static let smallRegularFontFamily = Roboto
    public static let smallRegularFontSize = 14
    public static let smallRegularFontWeight = Regular
    public static let smallRegularLineHeight = 150%
    public static let smallSemiBoldFontFamily = Roboto
    public static let smallSemiBoldFontSize = 14
    public static let smallSemiBoldFontWeight = SemiBold
    public static let smallSemiBoldLineHeight = 150%
    public static let success10Blur = 18
    public static let success10Color = #b1db8833
    public static let success10Spread = 2
    public static let success10Type = dropShadow
    public static let success10X = 0
    public static let success10Y = 4
    public static let success20Blur = 18
    public static let success20Color = #b1db8833
    public static let success20Spread = 50
    public static let success20Type = dropShadow
    public static let success20X = 0
    public static let success20Y = 8
    public static let successS100 = #b1db88
    public static let successS200 = #90cc54
    public static let successS300 = #79c131
    public static let successS400 = #558722
    public static let successS50 = #f2f9ea
    public static let successS500 = #4a761e
    public static let successS75 = #c8e6ab
    public static let textCaseCapitalize = capitalize
    public static let textCaseUppercase = uppercase
    public static let textDecorationLineThrough = line-through
    public static let textDecorationUnderline = underline
    public static let tokenSetOrder0 = globals
    public static let tokenSetOrder1 = Core/__colors
    public static let tokenSetOrder2 = Core/__layout
    public static let tokenSetOrder3 = Core/__typography
    public static let tokenSetOrder4 = Components/__buttons
    public static let tokenSetOrder5 = Modules/__research
    public static let warning20Blur = 18
    public static let warning20Color = #ffdb8633
    public static let warning20Spread = 50
    public static let warning20Type = dropShadow
    public static let warning20X = 0
    public static let warning20Y = 8
    public static let warningW100 = #ffdb86
    public static let warningW200 = #ffcc52
    public static let warningW300 = #ffc12e
    public static let warningW400 = #b38720
    public static let warningW50 = #fff9ea
    public static let warningW500 = #9c761c
    public static let warningW75 = #ffe6a9
    public static let white = #fff
    public static let xSmallBoldFontFamily = Roboto
    public static let xSmallBoldFontSize = 11
    public static let xSmallBoldFontWeight = Bold
    public static let xSmallBoldLineHeight = 140%
    public static let xSmallMediumFontFamily = Roboto
    public static let xSmallMediumFontSize = 11
    public static let xSmallMediumFontWeight = Medium
    public static let xSmallMediumLineHeight = 140%
    public static let xSmallRegularFontFamily = Roboto
    public static let xSmallRegularFontSize = 11
    public static let xSmallRegularFontWeight = Regular
    public static let xSmallRegularLineHeight = 140%
    public static let xSmallSemiBoldFontFamily = Roboto
    public static let xSmallSemiBoldFontSize = 11
    public static let xSmallSemiBoldFontWeight = SemiBold
    public static let xSmallSemiBoldLineHeight = 140%
}
