
//
// designTokens/ios-swift/DesignSystem+Struct.swift
//

// Do not edit directly
// Generated on Tue, 21 Mar 2023 10:48:19 GMT


import UIKit

internal struct DesignSystemStruct {
    internal static let accent20Blur = 18
    internal static let accent20Color = #9dd4d833
    internal static let accent20Spread = 50
    internal static let accent20Type = dropShadow
    internal static let accent20X = 0
    internal static let accent20Y = 8
    internal static let accentA100 = #9dd4d8
    internal static let accentA200 = #73c2c7
    internal static let accentA300 = #56b5bc
    internal static let accentA400 = #3c7f84
    internal static let accentA50 = #eef8f8
    internal static let accentA500 = #346e73
    internal static let accentA75 = #bae1e4
    internal static let baseBoldFontFamily = Roboto
    internal static let baseBoldFontSize = 16
    internal static let baseBoldFontWeight = Bold
    internal static let baseBoldLineHeight = 150%
    internal static let baseMediumFontFamily = Roboto
    internal static let baseMediumFontSize = 16
    internal static let baseMediumFontWeight = Medium
    internal static let baseMediumLineHeight = 150%
    internal static let baseRegularFontFamily = Roboto
    internal static let baseRegularFontSize = 16
    internal static let baseRegularFontWeight = Regular
    internal static let baseRegularLineHeight = 150%
    internal static let baseSemiBoldFontFamily = Roboto
    internal static let baseSemiBoldFontSize = 16
    internal static let baseSemiBoldFontWeight = SemiBold
    internal static let baseSemiBoldLineHeight = 150%
    internal static let black = #000000
    internal static let body = #061216
    internal static let borderDashAccent01Color = #bae1e4
    internal static let borderDashAccent01Style = dashed
    internal static let borderDashAccent01Width = 1
    internal static let borderDashPrimary01Color = #97adb4
    internal static let borderDashPrimary01Style = dashed
    internal static let borderDashPrimary01Width = 1
    internal static let borderLineAccent1Color = #bae1e4
    internal static let borderLineAccent1Style = solid
    internal static let borderLineAccent1Width = 1
    internal static let borderLinePrimary01Color = #97adb4
    internal static let borderLinePrimary01Style = solid
    internal static let borderLinePrimary01Width = 1
    internal static let borderRadius12 = 12
    internal static let borderRadius16 = 16
    internal static let borderRadius20 = 20
    internal static let borderRadius24 = 24
    internal static let borderRadius28 = 28
    internal static let borderRadius32 = 32
    internal static let borderRadius4 = 4
    internal static let borderRadius8 = 8
    internal static let borderWidth01 = 1
    internal static let borderWidth02 = 2
    internal static let borderWidth03 = 3
    internal static let borderWidth04 = 4
    internal static let btnSpacing12 = 12
    internal static let btnSpacing16 = 16
    internal static let btnSpacing20 = 20
    internal static let btnSpacing24 = 24
    internal static let btnSpacing4 = 4
    internal static let btnSpacing8 = 8
    internal static let buttonBorderDangerActiveColor = #ed3030
    internal static let buttonBorderDangerActiveStyle = solid
    internal static let buttonBorderDangerActiveWidth = 1
    internal static let buttonBorderDangerHoverColor = #a62222
    internal static let buttonBorderDangerHoverStyle = solid
    internal static let buttonBorderDangerHoverWidth = 1
    internal static let buttonBorderPrimaryActiveColor = #56b5bc
    internal static let buttonBorderPrimaryActiveStyle = solid
    internal static let buttonBorderPrimaryActiveWidth = 1
    internal static let buttonBorderPrimaryHoverColor = #3c7f84
    internal static let buttonBorderPrimaryHoverStyle = solid
    internal static let buttonBorderPrimaryHoverWidth = 1
    internal static let buttonBorderRadiusSm = 4
    internal static let buttonBorderRadiusXxxl = 24
    internal static let buttonBorderSecondaryActiveColor = #ef8b6d
    internal static let buttonBorderSecondaryActiveStyle = solid
    internal static let buttonBorderSecondaryActiveWidth = 1
    internal static let buttonBorderSecondaryHoverColor = #a7614c
    internal static let buttonBorderSecondaryHoverStyle = solid
    internal static let buttonBorderSecondaryHoverWidth = 1
    internal static let buttonBorderSuccessActiveColor = #79c131
    internal static let buttonBorderSuccessActiveStyle = solid
    internal static let buttonBorderSuccessActiveWidth = 1
    internal static let buttonBorderSuccessHoverColor = #558722
    internal static let buttonBorderSuccessHoverStyle = solid
    internal static let buttonBorderSuccessHoverWidth = 1
    internal static let buttonBorderWidthSm = 1
    internal static let buttonDangerActive = #ed3030
    internal static let buttonDangerClick = #f8aaaa
    internal static let buttonDangerHover = #a62222
    internal static let buttonDangerHoverAlt = #fdeaea
    internal static let buttonDisabled = #c1c4ce
    internal static let buttonInfoActive = #1eaaf9
    internal static let buttonInfoClick = #a3dcfd
    internal static let buttonInfoHover = #1577ae
    internal static let buttonInfoHoverAlt = #e9f7fe
    internal static let buttonPrimaryActive = #56b5bc
    internal static let buttonPrimaryClick = #bae1e4
    internal static let buttonPrimaryHover = #3c7f84
    internal static let buttonPrimaryHoverAlt = #eef8f8
    internal static let buttonSecondaryActive = #ef8b6d
    internal static let buttonSecondaryClick = #f8cfc3
    internal static let buttonSecondaryHover = #a7614c
    internal static let buttonSecondaryHoverAlt = #fdf3f0
    internal static let buttonSuccessActive = #79c131
    internal static let buttonSuccessClick = #c8e6ab
    internal static let buttonSuccessHover = #558722
    internal static let buttonSuccessHoverAlt = #f2f9ea
    internal static let buttonTextWhite = #fff
    internal static let colorAccent100 = UIColor(red: 0.616, green: 0.831, blue: 0.847, alpha: 1)
    internal static let colorAccent200 = UIColor(red: 0.451, green: 0.761, blue: 0.780, alpha: 1)
    internal static let colorAccent300 = UIColor(red: 0.337, green: 0.710, blue: 0.737, alpha: 1)
    internal static let colorAccent400 = UIColor(red: 0.235, green: 0.498, blue: 0.518, alpha: 1)
    internal static let colorAccent50 = UIColor(red: 0.933, green: 0.973, blue: 0.973, alpha: 1)
    internal static let colorAccent500 = UIColor(red: 0.204, green: 0.431, blue: 0.451, alpha: 1)
    internal static let colorAccent75 = UIColor(red: 0.729, green: 0.882, blue: 0.894, alpha: 1)
    internal static let colorBlack = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorDanger100 = UIColor(red: 0.961, green: 0.529, blue: 0.529, alpha: 1)
    internal static let colorDanger200 = UIColor(red: 0.941, green: 0.325, blue: 0.325, alpha: 1)
    internal static let colorDanger300 = UIColor(red: 0.929, green: 0.188, blue: 0.188, alpha: 1)
    internal static let colorDanger400 = UIColor(red: 0.651, green: 0.133, blue: 0.133, alpha: 1)
    internal static let colorDanger50 = UIColor(red: 0.992, green: 0.918, blue: 0.918, alpha: 1)
    internal static let colorDanger500 = UIColor(red: 0.569, green: 0.114, blue: 0.114, alpha: 1)
    internal static let colorDanger75 = UIColor(red: 0.973, green: 0.667, blue: 0.667, alpha: 1)
    internal static let colorGNormal180 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorGPrimary180 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorGPrimary270 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorGPrimary45 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorGPrimary90 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorGSecondary180 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorGSecondary270 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorGSecondary45 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorGSecondary90 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    internal static let colorInfo100 = UIColor(red: 0.490, green: 0.808, blue: 0.988, alpha: 1)
    internal static let colorInfo200 = UIColor(red: 0.267, green: 0.722, blue: 0.980, alpha: 1)
    internal static let colorInfo300 = UIColor(red: 0.118, green: 0.667, blue: 0.976, alpha: 1)
    internal static let colorInfo400 = UIColor(red: 0.082, green: 0.467, blue: 0.682, alpha: 1)
    internal static let colorInfo50 = UIColor(red: 0.914, green: 0.969, blue: 0.996, alpha: 1)
    internal static let colorInfo500 = UIColor(red: 0.071, green: 0.408, blue: 0.596, alpha: 1)
    internal static let colorInfo75 = UIColor(red: 0.639, green: 0.863, blue: 0.992, alpha: 1)
    internal static let colorNeutral10 = UIColor(red: 0.980, green: 0.980, blue: 0.984, alpha: 1)
    internal static let colorNeutral100 = UIColor(red: 0.471, green: 0.494, blue: 0.584, alpha: 1)
    internal static let colorNeutral20 = UIColor(red: 0.961, green: 0.961, blue: 0.969, alpha: 1)
    internal static let colorNeutral200 = UIColor(red: 0.412, green: 0.439, blue: 0.537, alpha: 1)
    internal static let colorNeutral30 = UIColor(red: 0.922, green: 0.925, blue: 0.937, alpha: 1)
    internal static let colorNeutral300 = UIColor(red: 0.353, green: 0.384, blue: 0.490, alpha: 1)
    internal static let colorNeutral40 = UIColor(red: 0.875, green: 0.878, blue: 0.898, alpha: 1)
    internal static let colorNeutral400 = UIColor(red: 0.306, green: 0.337, blue: 0.451, alpha: 1)
    internal static let colorNeutral50 = UIColor(red: 0.757, green: 0.769, blue: 0.808, alpha: 1)
    internal static let colorNeutral500 = UIColor(red: 0.247, green: 0.282, blue: 0.404, alpha: 1)
    internal static let colorNeutral60 = UIColor(red: 0.698, green: 0.710, blue: 0.761, alpha: 1)
    internal static let colorNeutral600 = UIColor(red: 0.196, green: 0.235, blue: 0.365, alpha: 1)
    internal static let colorNeutral70 = UIColor(red: 0.647, green: 0.663, blue: 0.722, alpha: 1)
    internal static let colorNeutral700 = UIColor(red: 0.129, green: 0.169, blue: 0.314, alpha: 1)
    internal static let colorNeutral80 = UIColor(red: 0.588, green: 0.608, blue: 0.675, alpha: 1)
    internal static let colorNeutral800 = UIColor(red: 0.071, green: 0.114, blue: 0.267, alpha: 1)
    internal static let colorNeutral90 = UIColor(red: 0.529, green: 0.553, blue: 0.627, alpha: 1)
    internal static let colorNeutral900 = UIColor(red: 0.020, green: 0.067, blue: 0.227, alpha: 1)
    internal static let colorPrimary100 = UIColor(red: 0.424, green: 0.545, blue: 0.580, alpha: 1)
    internal static let colorPrimary200 = UIColor(red: 0.176, green: 0.349, blue: 0.400, alpha: 1)
    internal static let colorPrimary300 = UIColor(red: 0.008, green: 0.216, blue: 0.278, alpha: 1)
    internal static let colorPrimary400 = UIColor(red: 0.004, green: 0.153, blue: 0.196, alpha: 1)
    internal static let colorPrimary50 = UIColor(red: 0.902, green: 0.922, blue: 0.929, alpha: 1)
    internal static let colorPrimary500 = UIColor(red: 0.004, green: 0.133, blue: 0.169, alpha: 1)
    internal static let colorPrimary75 = UIColor(red: 0.592, green: 0.678, blue: 0.706, alpha: 1)
    internal static let colorSecondary100 = UIColor(red: 0.965, green: 0.737, blue: 0.667, alpha: 1)
    internal static let colorSecondary200 = UIColor(red: 0.949, green: 0.624, blue: 0.525, alpha: 1)
    internal static let colorSecondary300 = UIColor(red: 0.937, green: 0.545, blue: 0.427, alpha: 1)
    internal static let colorSecondary400 = UIColor(red: 0.655, green: 0.380, blue: 0.298, alpha: 1)
    internal static let colorSecondary50 = UIColor(red: 0.992, green: 0.953, blue: 0.941, alpha: 1)
    internal static let colorSecondary500 = UIColor(red: 0.573, green: 0.333, blue: 0.259, alpha: 1)
    internal static let colorSecondary75 = UIColor(red: 0.973, green: 0.812, blue: 0.765, alpha: 1)
    internal static let colorSuccess100 = UIColor(red: 0.694, green: 0.859, blue: 0.533, alpha: 1)
    internal static let colorSuccess200 = UIColor(red: 0.565, green: 0.800, blue: 0.329, alpha: 1)
    internal static let colorSuccess300 = UIColor(red: 0.475, green: 0.757, blue: 0.192, alpha: 1)
    internal static let colorSuccess400 = UIColor(red: 0.333, green: 0.529, blue: 0.133, alpha: 1)
    internal static let colorSuccess50 = UIColor(red: 0.949, green: 0.976, blue: 0.918, alpha: 1)
    internal static let colorSuccess500 = UIColor(red: 0.290, green: 0.463, blue: 0.118, alpha: 1)
    internal static let colorSuccess75 = UIColor(red: 0.784, green: 0.902, blue: 0.671, alpha: 1)
    internal static let colorWarning100 = UIColor(red: 1.000, green: 0.859, blue: 0.525, alpha: 1)
    internal static let colorWarning200 = UIColor(red: 1.000, green: 0.800, blue: 0.322, alpha: 1)
    internal static let colorWarning300 = UIColor(red: 1.000, green: 0.757, blue: 0.180, alpha: 1)
    internal static let colorWarning400 = UIColor(red: 0.702, green: 0.529, blue: 0.125, alpha: 1)
    internal static let colorWarning50 = UIColor(red: 1.000, green: 0.976, blue: 0.918, alpha: 1)
    internal static let colorWarning500 = UIColor(red: 0.612, green: 0.463, blue: 0.110, alpha: 1)
    internal static let colorWarning75 = UIColor(red: 1.000, green: 0.902, blue: 0.663, alpha: 1)
    internal static let colorWhite = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    internal static let danger20Blur = 18
    internal static let danger20Color = #f5878733
    internal static let danger20Spread = 50
    internal static let danger20Type = dropShadow
    internal static let danger20X = 0
    internal static let danger20Y = 8
    internal static let dangerD100 = #f58787
    internal static let dangerD200 = #f05353
    internal static let dangerD300 = #ed3030
    internal static let dangerD400 = #a62222
    internal static let dangerD50 = #fdeaea
    internal static let dangerD500 = #911d1d
    internal static let dangerD75 = #f8aaaa
    internal static let fontColorShadeAccent = "#3c7f84"
    internal static let fontColorShadeDanger = "#a62222"
    internal static let fontColorShadeInfo = "#1577ae"
    internal static let fontColorShadePrimary = "#012732"
    internal static let fontColorShadeSecondary = "#a7614c"
    internal static let fontColorShadeSuccess = "#558722"
    internal static let fontColorShadeWarning = "#b38720"
    internal static let fontDefaultBlack = "#000000"
    internal static let fontDefaultColor = "#061216"
    internal static let fontDefaultWhite = "#fff"
    internal static let fontFamilyCourier = Courier Prime
    internal static let fontFamilyRoboto = Roboto
    internal static let fontSize11px = 11
    internal static let fontSize13px = 13
    internal static let fontSize14px = 14
    internal static let fontSize16px = 16
    internal static let fontSize18px = 18
    internal static let fontSize20px = 20
    internal static let fontSize23px = 23
    internal static let fontSize26px = 26
    internal static let fontSize29px = 29
    internal static let fontSize32px = 32
    internal static let fontSize36px = 36
    internal static let fontTint01 = "#c1c4ce"
    internal static let fontTint02 = "#b2b5c2"
    internal static let fontTint03 = "#a5a9b8"
    internal static let fontTint04 = "#969bac"
    internal static let fontUnderline = "underline"
    internal static let fontUppercase = "uppercase"
    internal static let fontWeightBold = Bold
    internal static let fontWeightItalic = Italic
    internal static let fontWeightMedium = Medium
    internal static let fontWeightRegular = Regular
    internal static let fontWeightSemiBold = SemiBold
    internal static let gradientNormal180 = linear-gradient(180deg, #fafafb 0%, #c1c4ce 100%)
    internal static let gradientPrimary180 = linear-gradient(180deg, #c1c4ce 0%, #56b5bc 100%)
    internal static let gradientPrimary270 = linear-gradient(270deg, #fff 0%, #56b5bc 100%)
    internal static let gradientPrimary45 = linear-gradient(45deg, #fff 0%, #56b5bc 100%)
    internal static let gradientPrimary90 = linear-gradient(90deg, #fff 0%, #56b5bc 100%)
    internal static let gradientSecondary180 = linear-gradient(180deg, #fff 0%, #ef8b6d 100%)
    internal static let gradientSecondary270 = linear-gradient(270deg, #fff 0%, #ef8b6d 100%)
    internal static let gradientSecondary45 = linear-gradient(45deg, #fff 0%, #ef8b6d 100%)
    internal static let gradientSecondary90 = linear-gradient(90deg, #fff 0%, #ef8b6d 100%)
    internal static let h1BoldFontFamily = Roboto
    internal static let h1BoldFontSize = 36
    internal static let h1BoldFontWeight = Bold
    internal static let h1BoldLineHeight = 140%
    internal static let h1MediumFontFamily = Roboto
    internal static let h1MediumFontSize = 36
    internal static let h1MediumFontWeight = Medium
    internal static let h1MediumLineHeight = 140%
    internal static let h1RegularFontFamily = Roboto
    internal static let h1RegularFontSize = 36
    internal static let h1RegularFontWeight = Regular
    internal static let h1RegularLineHeight = 140%
    internal static let h1SemiBoldFontFamily = Roboto
    internal static let h1SemiBoldFontSize = 36
    internal static let h1SemiBoldFontWeight = SemiBold
    internal static let h1SemiBoldLineHeight = 140%
    internal static let h2BoldFontFamily = Roboto
    internal static let h2BoldFontSize = 32
    internal static let h2BoldFontWeight = Bold
    internal static let h2BoldLineHeight = 140%
    internal static let h2MediumFontFamily = Roboto
    internal static let h2MediumFontSize = 32
    internal static let h2MediumFontWeight = Medium
    internal static let h2MediumLineHeight = 140%
    internal static let h2RegularFontFamily = Roboto
    internal static let h2RegularFontSize = 32
    internal static let h2RegularFontWeight = Regular
    internal static let h2RegularLineHeight = 140%
    internal static let h2SemiBoldFontFamily = Roboto
    internal static let h2SemiBoldFontSize = 32
    internal static let h2SemiBoldFontWeight = SemiBold
    internal static let h2SemiBoldLineHeight = 140%
    internal static let h3BoldFontFamily = Roboto
    internal static let h3BoldFontSize = 29
    internal static let h3BoldFontWeight = Bold
    internal static let h3BoldLineHeight = 140%
    internal static let h3MediumFontFamily = Roboto
    internal static let h3MediumFontSize = 29
    internal static let h3MediumFontWeight = Medium
    internal static let h3MediumLineHeight = 140%
    internal static let h3RegularFontFamily = Roboto
    internal static let h3RegularFontSize = 29
    internal static let h3RegularFontWeight = Regular
    internal static let h3RegularLineHeight = 140%
    internal static let h3SemiBoldFontFamily = Roboto
    internal static let h3SemiBoldFontSize = 29
    internal static let h3SemiBoldFontWeight = SemiBold
    internal static let h3SemiBoldLineHeight = 140%
    internal static let h4BoldFontFamily = Roboto
    internal static let h4BoldFontSize = 26
    internal static let h4BoldFontWeight = Bold
    internal static let h4BoldLineHeight = 140%
    internal static let h4MediumFontFamily = Roboto
    internal static let h4MediumFontSize = 26
    internal static let h4MediumFontWeight = Medium
    internal static let h4MediumLineHeight = 140%
    internal static let h4RegularFontFamily = Roboto
    internal static let h4RegularFontSize = 26
    internal static let h4RegularFontWeight = Regular
    internal static let h4RegularLineHeight = 140%
    internal static let h4SemiBoldFontFamily = Roboto
    internal static let h4SemiBoldFontSize = 26
    internal static let h4SemiBoldFontWeight = SemiBold
    internal static let h4SemiBoldLineHeight = 140%
    internal static let h5BoldFontFamily = Roboto
    internal static let h5BoldFontSize = 23
    internal static let h5BoldFontWeight = Bold
    internal static let h5BoldLineHeight = 140%
    internal static let h5MediumFontFamily = Roboto
    internal static let h5MediumFontSize = 23
    internal static let h5MediumFontWeight = Medium
    internal static let h5MediumLineHeight = 140%
    internal static let h5RegularFontFamily = Roboto
    internal static let h5RegularFontSize = 23
    internal static let h5RegularFontWeight = Regular
    internal static let h5RegularLineHeight = 140%
    internal static let h5SemiBoldFontFamily = Roboto
    internal static let h5SemiBoldFontSize = 23
    internal static let h5SemiBoldFontWeight = SemiBold
    internal static let h5SemiBoldLineHeight = 140%
    internal static let h6BoldFontFamily = Roboto
    internal static let h6BoldFontSize = 20
    internal static let h6BoldFontWeight = Bold
    internal static let h6BoldLineHeight = 140%
    internal static let h6MediumFontFamily = Roboto
    internal static let h6MediumFontSize = 20
    internal static let h6MediumFontWeight = Medium
    internal static let h6MediumLineHeight = 140%
    internal static let h6RegularFontFamily = Roboto
    internal static let h6RegularFontSize = 20
    internal static let h6RegularFontWeight = Regular
    internal static let h6RegularLineHeight = 140%
    internal static let h6SemiBoldFontFamily = Roboto
    internal static let h6SemiBoldFontSize = 20
    internal static let h6SemiBoldFontWeight = SemiBold
    internal static let h6SemiBoldLineHeight = 140%
    internal static let info20Blur = 18
    internal static let info20Color = #7dcefc33
    internal static let info20Spread = 50
    internal static let info20Type = dropShadow
    internal static let info20X = 0
    internal static let info20Y = 8
    internal static let infoI100 = #7dcefc
    internal static let infoI200 = #44b8fa
    internal static let infoI300 = #1eaaf9
    internal static let infoI400 = #1577ae
    internal static let infoI50 = #e9f7fe
    internal static let infoI500 = #126898
    internal static let infoI75 = #a3dcfd
    internal static let labelBoldFontFamily = Roboto
    internal static let labelBoldFontSize = 13
    internal static let labelBoldFontWeight = Bold
    internal static let labelBoldLineHeight = 140%
    internal static let labelMediumFontFamily = Roboto
    internal static let labelMediumFontSize = 13
    internal static let labelMediumFontWeight = Medium
    internal static let labelMediumLineHeight = 140%
    internal static let labelRegularFontFamily = Roboto
    internal static let labelRegularFontSize = 13
    internal static let labelRegularFontWeight = Regular
    internal static let labelRegularLineHeight = 140%
    internal static let labelSemiBoldFontFamily = Roboto
    internal static let labelSemiBoldFontSize = 13
    internal static let labelSemiBoldFontWeight = SemiBold
    internal static let labelSemiBoldLineHeight = 140%
    internal static let largeBoldFontFamily = Roboto
    internal static let largeBoldFontSize = 18
    internal static let largeBoldFontWeight = Bold
    internal static let largeBoldLineHeight = 150%
    internal static let largeMediumFontFamily = Roboto
    internal static let largeMediumFontSize = 18
    internal static let largeMediumFontWeight = Medium
    internal static let largeMediumLineHeight = 150%
    internal static let largeRegularFontFamily = Roboto
    internal static let largeRegularFontSize = 18
    internal static let largeRegularFontWeight = Regular
    internal static let largeRegularLineHeight = 150%
    internal static let largeSemiBoldFontFamily = Roboto
    internal static let largeSemiBoldFontSize = 18
    internal static let largeSemiBoldFontWeight = SemiBold
    internal static let largeSemiBoldLineHeight = 150%
    internal static let layoutBackgroundAccent = #eef8f8
    internal static let layoutBackgroundN10 = #fafafb
    internal static let layoutBackgroundN20 = #f5f5f7
    internal static let layoutBackgroundN30 = #ebecef
    internal static let layoutBackgroundN40 = #dfe0e5
    internal static let layoutBackgroundN50 = #c1c4ce
    internal static let layoutBackgroundPrimary = #e6ebed
    internal static let layoutBackgroundSecondary = #fdf3f0
    internal static let layoutBackgroundWhite = #fff
    internal static let layoutBorderRadius12 = 12
    internal static let layoutBorderRadius16 = 16
    internal static let layoutBorderRadius20 = 20
    internal static let layoutBorderRadius24 = 24
    internal static let layoutBorderRadius28 = 28
    internal static let layoutBorderRadius32 = 32
    internal static let layoutBorderRadius4 = 4
    internal static let layoutBorderRadius8 = 8
    internal static let layoutBorderWidth01 = 1
    internal static let layoutBorderWidth02 = 2
    internal static let layoutBorderWidth03 = 3
    internal static let layoutBorderWidth04 = 4
    internal static let layoutBoxShadowAccentBlur = 18
    internal static let layoutBoxShadowAccentColor = #9dd4d833
    internal static let layoutBoxShadowAccentSpread = 50
    internal static let layoutBoxShadowAccentType = dropShadow
    internal static let layoutBoxShadowAccentX = 0
    internal static let layoutBoxShadowAccentY = 8
    internal static let layoutBoxShadowDangerBlur = 18
    internal static let layoutBoxShadowDangerColor = #f5878733
    internal static let layoutBoxShadowDangerSpread = 50
    internal static let layoutBoxShadowDangerType = dropShadow
    internal static let layoutBoxShadowDangerX = 0
    internal static let layoutBoxShadowDangerY = 8
    internal static let layoutBoxShadowInfoBlur = 18
    internal static let layoutBoxShadowInfoColor = #7dcefc33
    internal static let layoutBoxShadowInfoSpread = 50
    internal static let layoutBoxShadowInfoType = dropShadow
    internal static let layoutBoxShadowInfoX = 0
    internal static let layoutBoxShadowInfoY = 8
    internal static let layoutBoxShadowPrimary10Blur = 15
    internal static let layoutBoxShadowPrimary10Color = #2d596614
    internal static let layoutBoxShadowPrimary10Spread = 0
    internal static let layoutBoxShadowPrimary10Type = dropShadow
    internal static let layoutBoxShadowPrimary10X = -3
    internal static let layoutBoxShadowPrimary10Y = 8
    internal static let layoutBoxShadowPrimary20Blur = 18
    internal static let layoutBoxShadowPrimary20Color = #6c8b9433
    internal static let layoutBoxShadowPrimary20Spread = 50
    internal static let layoutBoxShadowPrimary20Type = dropShadow
    internal static let layoutBoxShadowPrimary20X = 0
    internal static let layoutBoxShadowPrimary20Y = 8
    internal static let layoutBoxShadowPrimary5Blur = 18
    internal static let layoutBoxShadowPrimary5Color = #2d59660d
    internal static let layoutBoxShadowPrimary5Spread = 10
    internal static let layoutBoxShadowPrimary5Type = dropShadow
    internal static let layoutBoxShadowPrimary5X = 0
    internal static let layoutBoxShadowPrimary5Y = 8
    internal static let layoutBoxShadowSecondaryBlur = 18
    internal static let layoutBoxShadowSecondaryColor = #f6bcaa33
    internal static let layoutBoxShadowSecondarySpread = 50
    internal static let layoutBoxShadowSecondaryType = dropShadow
    internal static let layoutBoxShadowSecondaryX = 0
    internal static let layoutBoxShadowSecondaryY = 8
    internal static let layoutBoxShadowSuccess10Blur = 18
    internal static let layoutBoxShadowSuccess10Color = #b1db8833
    internal static let layoutBoxShadowSuccess10Spread = 2
    internal static let layoutBoxShadowSuccess10Type = dropShadow
    internal static let layoutBoxShadowSuccess10X = 0
    internal static let layoutBoxShadowSuccess10Y = 4
    internal static let layoutBoxShadowSuccess20Blur = 18
    internal static let layoutBoxShadowSuccess20Color = #b1db8833
    internal static let layoutBoxShadowSuccess20Spread = 50
    internal static let layoutBoxShadowSuccess20Type = dropShadow
    internal static let layoutBoxShadowSuccess20X = 0
    internal static let layoutBoxShadowSuccess20Y = 8
    internal static let layoutBoxShadowWarningBlur = 18
    internal static let layoutBoxShadowWarningColor = #ffdb8633
    internal static let layoutBoxShadowWarningSpread = 50
    internal static let layoutBoxShadowWarningType = dropShadow
    internal static let layoutBoxShadowWarningX = 0
    internal static let layoutBoxShadowWarningY = 8
    internal static let layoutDashedAccent01Color = #bae1e4
    internal static let layoutDashedAccent01Style = dashed
    internal static let layoutDashedAccent01Width = 1
    internal static let layoutDashedPrimary01Color = #97adb4
    internal static let layoutDashedPrimary01Style = dashed
    internal static let layoutDashedPrimary01Width = 1
    internal static let layoutOpacity10 = 10%
    internal static let layoutOpacity100 = 100%
    internal static let layoutOpacity20 = 20%
    internal static let layoutOpacity30 = 30%
    internal static let layoutOpacity40 = 40%
    internal static let layoutOpacity50 = 50%
    internal static let layoutOpacity60 = 60%
    internal static let layoutOpacity70 = 70%
    internal static let layoutOpacity80 = 80%
    internal static let layoutOpacity90 = 90%
    internal static let layoutSize100 = 100
    internal static let layoutSize12 = 12
    internal static let layoutSize16 = 16
    internal static let layoutSize20 = 20
    internal static let layoutSize200 = 200
    internal static let layoutSize24 = 24
    internal static let layoutSize28 = 28
    internal static let layoutSize32 = 32
    internal static let layoutSize36 = 36
    internal static let layoutSize4 = 4
    internal static let layoutSize40 = 40
    internal static let layoutSize44 = 44
    internal static let layoutSize48 = 48
    internal static let layoutSize52 = 52
    internal static let layoutSize56 = 56
    internal static let layoutSize60 = 60
    internal static let layoutSize8 = 8
    internal static let layoutSolidAccent01Color = #bae1e4
    internal static let layoutSolidAccent01Style = solid
    internal static let layoutSolidAccent01Width = 1
    internal static let layoutSolidPrimary01Color = #97adb4
    internal static let layoutSolidPrimary01Style = solid
    internal static let layoutSolidPrimary01Width = 1
    internal static let layoutSpacing12 = 12
    internal static let layoutSpacing16 = 16
    internal static let layoutSpacing2 = 2
    internal static let layoutSpacing20 = 20
    internal static let layoutSpacing24 = 24
    internal static let layoutSpacing28 = 28
    internal static let layoutSpacing32 = 32
    internal static let layoutSpacing36 = 36
    internal static let layoutSpacing4 = 4
    internal static let layoutSpacing40 = 40
    internal static let layoutSpacing44 = 44
    internal static let layoutSpacing48 = 48
    internal static let layoutSpacing52 = 52
    internal static let layoutSpacing56 = 56
    internal static let layoutSpacing60 = 60
    internal static let layoutSpacing8 = 8
    internal static let layoutSpacingMinus12 = -12
    internal static let layoutSpacingMinus16 = -16
    internal static let layoutSpacingMinus2 = -2
    internal static let layoutSpacingMinus20 = -20
    internal static let layoutSpacingMinus24 = -24
    internal static let layoutSpacingMinus28 = -28
    internal static let layoutSpacingMinus32 = -32
    internal static let layoutSpacingMinus36 = -36
    internal static let layoutSpacingMinus4 = -4
    internal static let layoutSpacingMinus40 = -40
    internal static let layoutSpacingMinus44 = -44
    internal static let layoutSpacingMinus48 = -48
    internal static let layoutSpacingMinus52 = -52
    internal static let layoutSpacingMinus56 = -56
    internal static let layoutSpacingMinus60 = -60
    internal static let layoutSpacingMinus8 = -8
    internal static let letterSpacing0 = 0%
    internal static let letterSpacing10 = 5%
    internal static let lineHeight140 = 140%
    internal static let lineHeight150 = 150%
    internal static let neutralN0 = #ffffff
    internal static let neutralN10 = #fafafb
    internal static let neutralN100 = #787e95
    internal static let neutralN20 = #f5f5f7
    internal static let neutralN200 = #697089
    internal static let neutralN30 = #ebecef
    internal static let neutralN300 = #5a627d
    internal static let neutralN40 = #dfe0e5
    internal static let neutralN400 = #4e5673
    internal static let neutralN50 = #c1c4ce
    internal static let neutralN500 = #3f4867
    internal static let neutralN60 = #b2b5c2
    internal static let neutralN600 = #323c5d
    internal static let neutralN70 = #a5a9b8
    internal static let neutralN700 = #212b50
    internal static let neutralN80 = #969bac
    internal static let neutralN800 = #121d44
    internal static let neutralN90 = #878da0
    internal static let neutralN900 = #05113a
    internal static let opacity10 = 10%
    internal static let opacity100 = 100%
    internal static let opacity20 = 20%
    internal static let opacity30 = 30%
    internal static let opacity40 = 40%
    internal static let opacity50 = 50%
    internal static let opacity60 = 60%
    internal static let opacity70 = 70%
    internal static let opacity80 = 80%
    internal static let opacity90 = 90%
    internal static let primary10LeftBlur = 15
    internal static let primary10LeftColor = #2d596614
    internal static let primary10LeftSpread = 0
    internal static let primary10LeftType = dropShadow
    internal static let primary10LeftX = -3
    internal static let primary10LeftY = 8
    internal static let primary20Blur = 18
    internal static let primary20Color = #6c8b9433
    internal static let primary20Spread = 50
    internal static let primary20Type = dropShadow
    internal static let primary20X = 0
    internal static let primary20Y = 8
    internal static let primary5Blur = 18
    internal static let primary5Color = #2d59660d
    internal static let primary5Spread = 10
    internal static let primary5Type = dropShadow
    internal static let primary5X = 0
    internal static let primary5Y = 8
    internal static let primaryP100 = #6c8b94
    internal static let primaryP200 = #2d5966
    internal static let primaryP300 = #023747
    internal static let primaryP400 = #012732
    internal static let primaryP50 = #e6ebed
    internal static let primaryP500 = #01222b
    internal static let primaryP75 = #97adb4
    internal static let refSize100 = 100
    internal static let refSize1000 = 1000
    internal static let refSize12 = 12
    internal static let refSize16 = 16
    internal static let refSize20 = 20
    internal static let refSize200 = 200
    internal static let refSize24 = 24
    internal static let refSize28 = 28
    internal static let refSize300 = 300
    internal static let refSize32 = 32
    internal static let refSize36 = 36
    internal static let refSize4 = 4
    internal static let refSize40 = 40
    internal static let refSize400 = 400
    internal static let refSize44 = 44
    internal static let refSize48 = 48
    internal static let refSize500 = 500
    internal static let refSize52 = 52
    internal static let refSize56 = 56
    internal static let refSize60 = 60
    internal static let refSize600 = 600
    internal static let refSize64 = 64
    internal static let refSize68 = 68
    internal static let refSize700 = 700
    internal static let refSize72 = 72
    internal static let refSize76 = 76
    internal static let refSize8 = 8
    internal static let refSize80 = 80
    internal static let refSize800 = 800
    internal static let refSize84 = 84
    internal static let refSize88 = 88
    internal static let refSize900 = 900
    internal static let refSize92 = 92
    internal static let refSize96 = 96
    internal static let refSpacing12 = 12
    internal static let refSpacing16 = 16
    internal static let refSpacing2 = 2
    internal static let refSpacing20 = 20
    internal static let refSpacing24 = 24
    internal static let refSpacing28 = 28
    internal static let refSpacing32 = 32
    internal static let refSpacing36 = 36
    internal static let refSpacing4 = 4
    internal static let refSpacing40 = 40
    internal static let refSpacing44 = 44
    internal static let refSpacing48 = 48
    internal static let refSpacing52 = 52
    internal static let refSpacing56 = 56
    internal static let refSpacing60 = 60
    internal static let refSpacing64 = 64
    internal static let refSpacing68 = 68
    internal static let refSpacing72 = 72
    internal static let refSpacing76 = 76
    internal static let refSpacing8 = 8
    internal static let refSpacing80 = 80
    internal static let secondary20Blur = 18
    internal static let secondary20Color = #f6bcaa33
    internal static let secondary20Spread = 50
    internal static let secondary20Type = dropShadow
    internal static let secondary20X = 0
    internal static let secondary20Y = 8
    internal static let secondaryS100 = #f6bcaa
    internal static let secondaryS200 = #f29f86
    internal static let secondaryS300 = #ef8b6d
    internal static let secondaryS400 = #a7614c
    internal static let secondaryS50 = #fdf3f0
    internal static let secondaryS500 = #925542
    internal static let secondaryS75 = #f8cfc3
    internal static let smallBoldFontFamily = Roboto
    internal static let smallBoldFontSize = 14
    internal static let smallBoldFontWeight = Bold
    internal static let smallBoldLineHeight = 150%
    internal static let smallCourierBoldFontFamily = Courier Prime
    internal static let smallCourierBoldFontSize = 14
    internal static let smallCourierBoldFontWeight = Bold
    internal static let smallCourierBoldLetterSpacing = 0%
    internal static let smallCourierBoldLineHeight = 150%
    internal static let smallCourierRegularFontFamily = Courier Prime
    internal static let smallCourierRegularFontSize = 14
    internal static let smallCourierRegularFontWeight = Regular
    internal static let smallCourierRegularLetterSpacing = 0%
    internal static let smallCourierRegularLineHeight = 140%
    internal static let smallCourierRegularitalicFontFamily = Courier Prime
    internal static let smallCourierRegularitalicFontSize = 14
    internal static let smallCourierRegularitalicFontWeight = Italic
    internal static let smallCourierRegularitalicLetterSpacing = 0%
    internal static let smallCourierRegularitalicLineHeight = 140%
    internal static let smallMediumFontFamily = Roboto
    internal static let smallMediumFontSize = 14
    internal static let smallMediumFontWeight = Medium
    internal static let smallMediumLineHeight = 150%
    internal static let smallRegularFontFamily = Roboto
    internal static let smallRegularFontSize = 14
    internal static let smallRegularFontWeight = Regular
    internal static let smallRegularLineHeight = 150%
    internal static let smallSemiBoldFontFamily = Roboto
    internal static let smallSemiBoldFontSize = 14
    internal static let smallSemiBoldFontWeight = SemiBold
    internal static let smallSemiBoldLineHeight = 150%
    internal static let success10Blur = 18
    internal static let success10Color = #b1db8833
    internal static let success10Spread = 2
    internal static let success10Type = dropShadow
    internal static let success10X = 0
    internal static let success10Y = 4
    internal static let success20Blur = 18
    internal static let success20Color = #b1db8833
    internal static let success20Spread = 50
    internal static let success20Type = dropShadow
    internal static let success20X = 0
    internal static let success20Y = 8
    internal static let successS100 = #b1db88
    internal static let successS200 = #90cc54
    internal static let successS300 = #79c131
    internal static let successS400 = #558722
    internal static let successS50 = #f2f9ea
    internal static let successS500 = #4a761e
    internal static let successS75 = #c8e6ab
    internal static let textCaseCapitalize = capitalize
    internal static let textCaseUppercase = uppercase
    internal static let textDecorationLineThrough = line-through
    internal static let textDecorationUnderline = underline
    internal static let tokenSetOrder0 = globals
    internal static let tokenSetOrder1 = Core/__colors
    internal static let tokenSetOrder2 = Core/__layout
    internal static let tokenSetOrder3 = Core/__typography
    internal static let tokenSetOrder4 = Components/__buttons
    internal static let tokenSetOrder5 = Modules/__research
    internal static let warning20Blur = 18
    internal static let warning20Color = #ffdb8633
    internal static let warning20Spread = 50
    internal static let warning20Type = dropShadow
    internal static let warning20X = 0
    internal static let warning20Y = 8
    internal static let warningW100 = #ffdb86
    internal static let warningW200 = #ffcc52
    internal static let warningW300 = #ffc12e
    internal static let warningW400 = #b38720
    internal static let warningW50 = #fff9ea
    internal static let warningW500 = #9c761c
    internal static let warningW75 = #ffe6a9
    internal static let white = #fff
    internal static let xSmallBoldFontFamily = Roboto
    internal static let xSmallBoldFontSize = 11
    internal static let xSmallBoldFontWeight = Bold
    internal static let xSmallBoldLineHeight = 140%
    internal static let xSmallMediumFontFamily = Roboto
    internal static let xSmallMediumFontSize = 11
    internal static let xSmallMediumFontWeight = Medium
    internal static let xSmallMediumLineHeight = 140%
    internal static let xSmallRegularFontFamily = Roboto
    internal static let xSmallRegularFontSize = 11
    internal static let xSmallRegularFontWeight = Regular
    internal static let xSmallRegularLineHeight = 140%
    internal static let xSmallSemiBoldFontFamily = Roboto
    internal static let xSmallSemiBoldFontSize = 11
    internal static let xSmallSemiBoldFontWeight = SemiBold
    internal static let xSmallSemiBoldLineHeight = 140%
}
